//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawTestResultsTransmission.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_report
    {
        public long id { get; set; }
        public System.Guid exam_id { get; set; }
        public string report { get; set; }
        public System.DateTime created_at { get; set; }
        public string status { get; set; }
    }
}
